name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      make_a_release:
        description: "Make a release"
        type: boolean
        required: false
        default: false
  schedule:
    # Runs every 7 days
    - cron: '0 0 */7 * *'

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    name: Build on ${{ matrix.friendly_name }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            friendly_name: "Linux (Ubuntu)"
          # - os: macos-latest
          #   platform: mac
          #   friendly_name: "macOS"
          - os: windows-latest
            platform: windows
            friendly_name: "Windows"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Force VCPKG_BUILD_TYPE to release
        shell: bash
        run: |
          find ./vcpkg/triplets -type f -exec sh -c "echo 'set(VCPKG_BUILD_TYPE release)' >> \"\$1\"" _ {} \;

      - name: Read version from version.txt
        shell: bash
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Replace <VERSION> in platform files
        shell: bash
        run: |
          sed -i "s/<VERSION>/${{ env.VERSION }}/g" platform/linux/orientview.desktop
          sed -i "s/<VERSION>/${{ env.VERSION }}/g" platform/mac/Info.plist
          sed -i "s/<VERSION>/${{ env.VERSION }}/g" platform/windows/orientview.rc

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y nasm bison libxi-dev libxtst-dev '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev libxkbcommon-dev libxkbcommon-x11-dev

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install"

      - name: Build and install
        run: cmake --build build --config Release --target install

      - name: Zip the installed artifacts (Unix)
        if: runner.os != 'Windows'
        run: |
          cd ${{ github.workspace }}/install
          zip -r "orientview-${{ env.VERSION }}-${{ matrix.platform }}.zip" .
    
      - name: Zip the installed artifacts (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $OutputPath = "${{ github.workspace }}\install\orientview-${{ env.VERSION }}-${{ matrix.platform }}.zip"
          Compress-Archive -Path "${{ github.workspace }}\install\*" -DestinationPath $OutputPath

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "platform-binaries"
          path: "install/orientview-*.zip"

      - name: Create a GitHub release
        if: ${{ github.event.inputs.make_a_release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "OrientView v${{ env.VERSION }}"
          files: "install/orientview-*.zip"
          generate_release_notes: true
          make_latest: true
